[phases.setup]
commands = [
    "python3 -m venv /opt/venv"
]

[phases.install]
commands = [
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
command = ". /opt/venv/bin/activate && python bot.py"
